#!/usr/bin/env sh

# load script additions manually (BigSur)
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_placement             second_child
yabai -m config window_topmost               on

# window opacity
yabai -m config window_opacity               on
yabai -m config normal_window_opacity        0.96
yabai -m config active_window_opacity        1.0
yabai -m config window_shadow                off

# window border
yabai -m config window_border                off
#yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xffff6600
yabai -m config normal_window_border_color   0xff004d99

# splitting ratio
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on

# mouse support
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# layout space settings
yabai -m config layout                       bsp
#yabai -m config top_padding                  10
#yabai -m config bottom_padding               10
#yabai -m config left_padding                 10
#yabai -m config right_padding                10
#yabai -m config window_gap                   5

# spacebar padding
SPACEBAR_HEIGHT=$(spacebar -m config height)
yabai -m config external_bar all:$SPACEBAR_HEIGHT:0

# space labels
yabai -m space 1 --label browser
yabai -m space 2 --label term
yabai -m space 3 --label ide
yabai -m space 4 --label slack
yabai -m space 5 --label notes
yabai -m space 6 --label browseretc
yabai -m space 7 --label games
yabai -m space 8 --label meet
yabai -m space 9 --label mail
yabai -m space 10 --label music

# layout overrides
## by space
yabai -m config --space games layout float

## by title/app
#yabai -m rule --add title='Settings'                          manage=off
#yabai -m rule --add title='Configur'                          manage=off
#yabai -m rule --add title='Preferences'                       manage=off
#yabai -m rule --add title='Preferences' app="^GoLand$"        manage=on
#yabai -m rule --add title='Information'                       manage=off
yabai -m rule --add app="^System Preferences$"                manage=off

# apps bindings to space
yabai -m rule --add title="Google Chrome - Sebastian (finn.auto)$"      space=browser
yabai -m rule --add app="^iTerm$"     space=term
yabai -m rule --add app="^Alacritty$" space=term
yabai -m rule --add app="^GoLand$"    space=ide
yabai -m rule --add app="^PyCharm$"   space=ide
yabai -m rule --add app="^VSCode$"    space=ide
yabai -m rule --add app="^Slack$"     space=slack
yabai -m rule --add app="^Notes$"     space=notes
yabai -m rule --add title="Google Chrome - Seba (Schattian)$"       space=browseretc
yabai -m rule --add app="^Steam$"     space=games manage=off
yabai -m rule --add app="^Discord$"   space=meet  manage=off  grid=1:1:0:0:1:1
yabai -m rule --add app="^Zoom$"      space=meet  manage=off  grid=1:1:0:0:1:1
yabai -m rule --add app="^Mail$"      space=mail
yabai -m rule --add app="^Calendar$"  space=mail
yabai -m rule --add app="^Spotify$"   space=music


#yabai -m config external_bar off:45:0

echo "yabai configuration loaded.."
